'''版本号'''
__version__ = '0.1.0'
'''作者'''
__author__ = '丁伟东'
'''标题'''
__title__ = 'pySourceControl'
'''描述'''
__description__ = 'pySourceControl: APIs for some source control tools.'
'''链接'''
__url__ = 'https://github.com/Weydon-Ding/pySourceControl'
'''邮件'''
__email__ = 'Weydon-Ding@outlook.com'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Copyright (c) 2023 丁伟东'